{dede:noteinfo notename="81中文小说封面（月点击1-10）" channelid="99" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.81zw.com/modules/article/toplist.php?sort=monthvisit&page=(*)"
startid="1" endid="10" addv="1" urlrule="area" musthas=""
 nothas="html" listpic="0" usemore="0"}
    {dede:addurls}http://www.81zw.com/modules/article/toplist.php?sort=monthvisit{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}状态</th>{/dede:areastart}
    {dede:areaend}<div class="pages">{/dede:areaend}
{/dede:listrule}
