{dede:noteinfo notename="笔下文学-和嫂子同居的日子" channelid="1" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="desc"
  isref="yes" exptime="10" usemore="1" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="(#)"
startid="1" endid="" addv="1" urlrule="area" musthas="html"
 nothas="" listpic="0" usemore="1"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}[(#)=>http://www.bxwx.org/b/71/71410/index.html; (*)=>1-2; typeid=>508]{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<!--列表内容开始-->{/dede:areastart}
    {dede:areaend}<!--列表内容结束-->{/dede:areaend}
{/dede:listrule}
