{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}打个电话给大侠{/dede:field}
{dede:field name='writer'}剑西来{/dede:field}
{dede:field name='source'}都市言情{/dede:field}
{dede:field name='pubdate'}2015-12-24{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='bookurl'}http://www.23wx.com/html/56/56815/{/dede:field}
{dede:field name='copynid'}37{/dede:field}
{dede:field name='overtag'}连载中{/dede:field}
{dede:field name='bookimg'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c151224/145091Y1095O0-22P3.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c151224/145091Y1095O0-22P3_lit.jpg{/dede:field}
