
   {dede:match}ÄÚÈİ¼ò½é£º</b></p>[ÄÚÈİ]<p style="display:none" id="sidename">{/dede:match}
   {dede:trim replace=""}<a([^>]*)>(.*)</a>{/dede:trim}
{dede:trim replace=""}<script([^>]*)>(.*)</script>{/dede:trim}
{dede:trim replace=""}<!--(.*)-->{/dede:trim}
{dede:trim replace=""}<table([^>]*)>(.*)</table>{/dede:trim}
{dede:trim replace=""}<div([^>]*)>(.*)</div>{/dede:trim}
{dede:trim replace=""}<p([^.]*)>{/dede:trim}
{dede:trim replace=""}</p>{/dede:trim}
   {dede:function}{/dede:function}
