{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}冠军之心{/dede:field}
{dede:field name='writer'}林海听涛{/dede:field}
{dede:field name='source'}都市言情{/dede:field}
{dede:field name='pubdate'}2015-12-24{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;“当然不是啦！只有在足球上，我才有远不止三分钟的热度呢！”<br />
　　“所以之前我们列举的那些都只是您三分钟热度的产物？”<br />
　　“没错。那些都只是我的爱好。”<br />
　　“那足球呢？足球不是您的爱好吗？”<br />
　　“当然不是，足球是爱！”<br />
　　这是一个有爱的故事。<br />{/dede:field}
{dede:field name='bookurl'}http://www.23wx.com/html/57/57341/{/dede:field}
{dede:field name='copynid'}37{/dede:field}
{dede:field name='overtag'}连载中{/dede:field}
{dede:field name='bookimg'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c151224/145091Y11MP-34061.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c151224/145091Y11MP-34061_lit.jpg{/dede:field}
