{dede:noteinfo notename="顶点小说封面采集（总点击1-10）" channelid="99" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="desc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.23wx.com/top/allvisit_(*).html"
startid="1" endid="10" addv="1" urlrule="area" musthas="/book/"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.23wx.com/top/monthvisit_1.html
http://www.23wx.com/top/allvisit_1.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<table style="width:736px{/dede:areastart}
    {dede:areaend}</table>{/dede:areaend}
{/dede:listrule}
