{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}妖孽学霸{/dede:field}
{dede:field name='writer'}维斯特帕列{/dede:field}
{dede:field name='source'}都市言情{/dede:field}
{dede:field name='pubdate'}2015-12-24{/dede:field}
{dede:field name='body'}&nbsp;&nbsp;&nbsp;&nbsp;简介：学霸分为三种，第一种高级学霸，他们是各自领域的顶尖存在，比如袁隆平、高琨；第二种传奇学霸，他们的影响力远远超过了自身涉及的领域，对整个时代产生影响，比如费米、图灵；第三种神级学霸，他们影响着整个人类文明的发展，比如爱因斯坦、牛顿。在此之外还有一种妖孽，他们不仅在科研领域远超群伦，在其他领域同样做到了凡人做不到的事情，柴恩博士在45年获得诺贝尔奖，七年后在赫尔辛基奥运会上摘取金牌；尼尔斯－波尔，二十世纪最伟大的物理学家之一，同时还是丹麦国家队的守门员；当然还有薛定谔，除了那只著名的猫，还有无数让人艳羡不已的风流韵事。而吕丘建正是要成为这第四种学霸。<br />{/dede:field}
{dede:field name='bookurl'}http://www.23wx.com/html/57/57730/{/dede:field}
{dede:field name='copynid'}37{/dede:field}
{dede:field name='overtag'}连载中{/dede:field}
{dede:field name='bookimg'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}
{dede:img ddimg='' text='图 1'}/uploads/allimg/c151224/145091Y101GZ-1c17.jpg{/dede:img}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c151224/145091Y101GZ-1c17_lit.jpg{/dede:field}
